#!/usr/bin/python2
import os
import sys
import compizconfig

command, filename = sys.argv[1:]
filename = os.path.abspath(filename)

context = compizconfig.Context()
if command == "export":
    context.Export(filename, skipDefaults=True)
elif command == "import":
    context.Import(filename, False)
