#!/bin/sh

dir=$(dirname $(readlink -f $0))
backup_dir="$dir.bkp.$(date --rfc-3339=ns)"
files="tmux.conf tmux vimrc vim zshrc zsh screenrc gitignore gitconfig xmonad editorconfig powerline fonts config/powerline"

echo "Installing symlinks to: $dir"

mkdir -p "$backup_dir"

echo "Updating submodules"
git submodule update --init

for file_pair in $files ; do
    file="${file_pair%%:*}"
    if [ "$file" = "$file_pair" ] ; then
        target_dir="$HOME/."
    else
        target_dir="$HOME/.${file_pair##*:}/"
    fi
    target_file="$target_dir$file"

    echo "Installing dotfile: $file"
    mv "$target_file" "$backup_dir/"
    ln -s "$dir/$file" "$target_file"
done


# Install Gnome Terminal configuration
gconftool-2 --dump '/apps/gnome-terminal' > "$backup_dir/gnome-terminal.xml"
gconftool-2 --load gnome-terminal.xml

pip install --user ./powerline/
