#!/bin/sh

BASEDIR=$(dirname $0)

# Restore WiFi networks
sudo cp "$1/wifi-networks"/* /etc/NetworkManager/system-connections/
sudo chown root.root /etc/NetworkManager/system-connections/*
sudo chmod 600 /etc/NetworkManager/system-connections/*

# Restore SSH keys
cp "$1/ssh"/* ~/.ssh/

# Restore Compiz Settings
python $BASEDIR/ccsm import "$1/compiz.profile"
