#!/bin/sh
set -e

base_dir=$(dirname $(dirname $(realpath $0)))

mkdir -p "$1"

# Backup package information
mkdir -p "$1/apt/"
dpkg --get-selections > "$1/apt/package.list"
sudo cp -R /etc/apt/sources.list* "$1/apt/"
sudo apt-key exportall > "$1/apt/repo.keys"

# Backup WiFi networks
mkdir "$1/wifi-networks/"
sudo cp /etc/NetworkManager/system-connections/* "$1/wifi-networks/"

# Backup OBS configuration
mkdir "$1/obs-studio/"
sudo cp ~/.config/obs-studio/* "$1/obs-studio/"

## Backup SSH keys (commented because my SSH config isn't useful anymore)
# mkdir "$1/ssh/"
# cp ~/.ssh/* "$1/ssh/"

# Backup Compiz Settings
$base_dir/scripts/ccsm export "$1/compiz.profile"
