#!/bin/sh

base_dir=$(dirname $(dirname $(realpath $0)))
backup_dir="$base_dir.bkp.$(date --rfc-3339=ns)"
files="tmux.conf tmux config/direnv config/starship.toml config/nvim config/ptpython config/pip inputrc profile zprofile zshrc startup.py screenrc gitignore gitconfig editorconfig fonts pyenv/version ipython/profile_default/ipython_config.py"

echo "Installing symlinks to: $base_dir"

mkdir -p "$backup_dir"
mkdir -p "$HOME/.pyenv"

for file_pair in $files ; do
    file="${file_pair%%:*}"
    if [ "$file" = "$file_pair" ] ; then
        target_dir="$HOME/."
    else
        target_dir="$HOME/.${file_pair##*:}/"
    fi
    target_file="$target_dir$file"

    echo "Installing dotfile: $file"
    mv "$target_file" "$backup_dir/"
    ln -s "$base_dir/$file" "$target_file"
done


# Install Gnome Terminal configuration
dconf dump "/org/gnome/terminal/" > "$backup_dir/gnome-terminal.dconf"
dconf load "/org/gnome/terminal/" < gnome-terminal.dconf

# Install other Gnome settings
dconf dump "/" > "$backup_dir/gnome-settings.dconf"
dconf load "/" < gnome-settings.dconf
